{% set data = load_setup_py_data() %}

package:
  name: hcrystalball
  version: {{ data.get('version')}}

source:
   path: ..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}  
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - numpy x.x
    - pandas
    - scipy
    - scikit-learn
    - workalendar
    - matplotlib
  run:
    - python
    - numpy x.x
    - pandas
    - scipy
    - scikit-learn
    - workalendar
    - matplotlib
    - statsmodels=0.11 # SmoothingWrappers
    - fbprophet=0.6 # ProphetWrapper
    - matplotlib # for plotting in model selection
    - tqdm # interactive progress bar
    - ipywidgets # interactive progress bar
    - jupyterlab # run examples, interactive progress bar
    - nodejs # interactive progress bar
    - sphinx # to build docs
    - sphinx-automodapi # to build docs
    - nbsphinx # to build docs
    - sphinx_rtd_theme # to build docs
    - sphinx-gallery # to build docs
    - black # to format the code
  # - prefect # to execute model selection in parallel
    - pip
    - pmdarima=1.5.3 # SarimaxWrapper, version 1.6.1 downloads cython and makes prophet fail
    - tbats=1.0.10 #(T)BATSWrapper, pinning patch version needed to to change in 1.0.3
    - pytest # to run tests
    - pytest-cov # to run tests    

test:
  requires:
    - pytest
    - pytest-cov
    - coverage
    - coveralls
  commands:
    - pytest    

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}

summary: {{ data.get('description') }}    